version: '3.0'
services:
  mask2former:
    container_name: mask2former-gpu
    image: thegeeksdiary/mask2former-jupyter-gpu:latest
    restart: unless-stopped
    # uncomment the below to map the notebooks from your machine inside the docker container - please make sure to change the path applicable to you.
    volumes:
      - ./notebooks:/environment/notebooks
      - ./data:/environment/data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - '8889:8888'
    networks:
      - jupyter
networks:
  jupyter:
    driver: bridge
