version: '3.0'
services:
  tensorflow:
    container_name: pytorch-gpu
    image: thegeeksdiary/pytorch-jupyter-gpu:latest
    restart: unless-stopped
    # uncomment the below to map the notebooks from your machine inside the docker container - please make sure to change the path applicable to you.
    volumes:
      - ./notebooks:/environment/notebooks
      - ./data:/environment/data
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - '8888:8888'
    networks:
      - jupyter
networks:
  jupyter:
    driver: bridge
